/**
 * Normalized toast payload consumed by the toast store and UI.
 * Callers usually pass `ToastOptions` or a string to `toast()`.
 */
export interface Toast {
  /** Internal unique identifier generated by the toast store. */
  id: number
  /** Text content displayed to the user. */
  message: string
  /** Auto-dismiss delay in milliseconds. Defaults to `3000`. */
  duration: number
}

interface ToastOptions {
  message: string
  duration?: number
}

type ToastOptionsOrString = ToastOptions | string
type Listener = () => void

let toastQueue: Toast[] = []
const listeners = new Set<Listener>()

let id = 0
let current: Toast | null = null

// `useSyncExternalStore` requires a referentially stable snapshot when data
// hasn't changed. Returning `current` directly avoids creating a fresh object.
function getSnapshot() {
  return current
}

function subscribe(listener: Listener) {
  listeners.add(listener)

  return () => {
    listeners.delete(listener)
  }
}

function emitChange() {
  listeners.forEach((listener) => listener())
}

function showNext() {
  const next = toastQueue.shift()

  if (next) {
    current = next
    emitChange()
  }
}

function dispose() {
  if (current === null) {
    return
  }

  current = null

  if (toastQueue.length === 0) {
    emitChange()
    return
  }

  showNext()
}

function clear() {
  current = null
  toastQueue = []
  emitChange()
}

function normalizeToast(optionsOrString: ToastOptionsOrString): Toast {
  const { message, duration = 3000 } =
    typeof optionsOrString === 'string'
      ? { message: optionsOrString }
      : optionsOrString

  return {
    id: ++id,
    message,
    duration,
  }
}

export function toast(optionsOrString: ToastOptionsOrString) {
  const normalized = normalizeToast(optionsOrString)

  if (current === null) {
    current = normalized
    emitChange()
  } else {
    toastQueue.push(normalized)
  }

  return normalized.id
}

export const toastStore = {
  clear,
  dispose,
  getSnapshot,
  subscribe,
}
