ALTER TABLE "permissions"
ADD COLUMN "group" TEXT NOT NULL DEFAULT '',
ADD COLUMN "label" TEXT NOT NULL DEFAULT '',
ADD COLUMN "deprecated" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "permissions"
ALTER COLUMN "group" DROP DEFAULT,
ALTER COLUMN "label" DROP DEFAULT;
