// import { defineConfig } from 'eslint/config'
// import eslintPluginJsonc from 'eslint-plugin-jsonc'

// console.log(eslintPluginJsonc.configs['flat/recommended-with-json'])

// export function createJsonConfig() {
//   return defineConfig(
//     ...eslintPluginJsonc.configs['flat/recommended-with-json'],

//     {
//       files: ['package.json', '**/package.json'],
//       rules: {
//         'jsonc/sort-array-values': [
//           'error',
//           {
//             order: {
//               type: 'asc',
//             },
//             pathPattern: '^files$',
//           },
//         ],
//         'jsonc/sort-keys': [
//           'error',
//           {
//             order: [
//               'name',
//               'version',
//               'private',
//               'packageManager',
//               'description',
//               'author',
//               'license',
//               'type',
//               'exports',
//               'main',
//               'types',
//               'files',
//               'scripts',
//               'peerDependencies',
//               'peerDependenciesMeta',
//               'dependencies',
//               'devDependencies',
//               'engines',
//               'pnpm',
//             ],
//             pathPattern: '^$',
//           },
//           {
//             order: {
//               type: 'asc',
//             },
//             pathPattern:
//               '^(?:dev|peer|optional|bundled)?[Dd]ependencies(Meta)?$',
//           },
//           {
//             order: {
//               type: 'asc',
//             },
//             pathPattern: '^(?:resolutions|overrides|pnpm.overrides)$',
//           },
//           {
//             order: ['types', 'import', 'require', 'default'],
//             pathPattern: '^exports.*$',
//           },
//         ],
//       },
//     },

//     {
//       files: [
//         'tsconfig.json',
//         'tsconfig.*.json',
//         '**/tsconfig.json',
//         '**/tsconfig.*.json',
//       ],
//       rules: {
//         'jsonc/sort-keys': [
//           'error',
//           {
//             order: [
//               'references',
//               'extends',
//               'compilerOptions',
//               'files',
//               'include',
//               'exclude',
//             ],
//             pathPattern: '^$',
//           },
//           {
//             order: [
//               'incremental',
//               'composite',
//               'tsBuildInfoFile',
//               'disableSourceOfProjectReferenceRedirect',
//               'disableSolutionSearching',
//               'disableReferencedProjectLoad',
//               'target',
//               'jsx',
//               'jsxFactory',
//               'jsxFragmentFactory',
//               'jsxImportSource',
//               'lib',
//               'moduleDetection',
//               'noLib',
//               'reactNamespace',
//               'useDefineForClassFields',
//               'emitDecoratorMetadata',
//               'experimentalDecorators',
//               'libReplacement',
//               'baseUrl',
//               'rootDir',
//               'rootDirs',
//               'customConditions',
//               'module',
//               'moduleResolution',
//               'moduleSuffixes',
//               'noResolve',
//               'paths',
//               'resolveJsonModule',
//               'resolvePackageJsonExports',
//               'resolvePackageJsonImports',
//               'typeRoots',
//               'types',
//               'allowArbitraryExtensions',
//               'allowImportingTsExtensions',
//               'allowUmdGlobalAccess',
//               'allowJs',
//               'checkJs',
//               'maxNodeModuleJsDepth',
//               'strict',
//               'strictBindCallApply',
//               'strictFunctionTypes',
//               'strictNullChecks',
//               'strictPropertyInitialization',
//               'allowUnreachableCode',
//               'allowUnusedLabels',
//               'alwaysStrict',
//               'exactOptionalPropertyTypes',
//               'noFallthroughCasesInSwitch',
//               'noImplicitAny',
//               'noImplicitOverride',
//               'noImplicitReturns',
//               'noImplicitThis',
//               'noPropertyAccessFromIndexSignature',
//               'noUncheckedIndexedAccess',
//               'noUnusedLocals',
//               'noUnusedParameters',
//               'useUnknownInCatchVariables',
//               'declaration',
//               'declarationDir',
//               'declarationMap',
//               'downlevelIteration',
//               'emitBOM',
//               'emitDeclarationOnly',
//               'importHelpers',
//               'importsNotUsedAsValues',
//               'inlineSourceMap',
//               'inlineSources',
//               'mapRoot',
//               'newLine',
//               'noEmit',
//               'noEmitHelpers',
//               'noEmitOnError',
//               'outDir',
//               'outFile',
//               'preserveConstEnums',
//               'preserveValueImports',
//               'removeComments',
//               'sourceMap',
//               'sourceRoot',
//               'stripInternal',
//               'allowSyntheticDefaultImports',
//               'esModuleInterop',
//               'forceConsistentCasingInFileNames',
//               'isolatedDeclarations',
//               'isolatedModules',
//               'preserveSymlinks',
//               'verbatimModuleSyntax',
//               'erasableSyntaxOnly',
//               'skipDefaultLibCheck',
//               'skipLibCheck',
//             ],
//             pathPattern: '^compilerOptions$',
//           },
//         ],
//       },
//     }
//   )
// }
