/**
 * Normalized notification payload consumed by the notification store and UI.
 * Callers usually pass `Omit<Notification, 'id'>` to `notify()`.
 */
export interface Notification {
  /** Internal unique identifier generated by the notification store. */
  id: number
  /** Visual variant for the notification. Defaults to `'info'`. */
  type?: 'info' | 'success' | 'warn' | 'danger'
  /** Notification title displayed above the message when provided. */
  title?: string
  /** Text content displayed to the user. */
  message: string
  /**
   * Auto-dismiss delay in milliseconds.
   * Use `'never'` to keep the notification visible until it is dismissed or
   * replaced.
   * Defaults to `3000`.
   */
  duration?: number | 'never'
  /**
   * When `true`, the notification jumps to the front of the queue and replaces
   * the currently displayed notification immediately.
   */
  imperative?: boolean
  /** Callback invoked when the notification leaves the screen. */
  onDispose?: () => void
}

type NotifyOptionsOrString = Omit<Notification, 'id'> | string
type Listener = () => void

let notificationQueue: Notification[] = []
const listeners = new Set<Listener>()

let id = 0
let current: Notification | null = null
let isDisposingCurrent = false

// `useSyncExternalStore` requires a referentially stable snapshot when data
// hasn't changed. Returning `current` directly avoids creating a fresh object.
function getSnapshot() {
  return current
}

function subscribe(listener: Listener) {
  listeners.add(listener)

  return () => {
    listeners.delete(listener)
  }
}

function emitChange() {
  listeners.forEach((listener) => listener())
}

function dispose() {
  if (current === null) {
    return
  }

  const dismissed = current
  current = null
  isDisposingCurrent = true
  runOnDispose(dismissed.onDispose)
  isDisposingCurrent = false

  if (notificationQueue.length === 0) {
    emitChange()
    return
  }

  showNext()
}

function remove(id: Notification['id']) {
  if (current?.id === id) {
    dispose()
    return
  }

  notificationQueue = notificationQueue.filter(
    (notification) => notification.id !== id
  )
}

function clear() {
  current = null
  notificationQueue = []
  isDisposingCurrent = false
  emitChange()
}

function runOnDispose(fn: Notification['onDispose']) {
  if (fn) {
    try {
      fn()
    } catch (error) {
      if (__DEV__) {
        console.error(
          'Failed to run callback:',
          error instanceof Error ? error.message : 'unknown reason'
        )
      }
    }
  }
}

function showNext() {
  const next = notificationQueue.shift()

  if (next) {
    current = next
    emitChange()
  }
}

function normalizeNotification(
  optionsOrString: NotifyOptionsOrString
): Notification {
  const {
    type = 'info',
    title,
    message,
    duration = 3000,
    imperative = false,
    onDispose,
  } = typeof optionsOrString === 'string'
    ? { message: optionsOrString }
    : optionsOrString

  return {
    id: ++id,
    type,
    title,
    message,
    duration,
    imperative,
    onDispose,
  }
}

export function notify(optionsOrString: NotifyOptionsOrString) {
  const normalized = normalizeNotification(optionsOrString)

  if (normalized.imperative) {
    if (current === null && !isDisposingCurrent) {
      current = normalized
      emitChange()

      return normalized.id
    }

    if (isDisposingCurrent) {
      notificationQueue.unshift(normalized)

      return normalized.id
    }

    const replaced = current
    current = normalized
    emitChange()
    runOnDispose(replaced?.onDispose)

    return normalized.id
  }

  if (current === null && !isDisposingCurrent) {
    current = normalized
    emitChange()
  } else {
    notificationQueue.push(normalized)
  }

  return normalized.id
}

export const notificationStore = {
  dispose,
  clear,
  getSnapshot,
  remove,
  subscribe,
}
