/**
 * Normalized notification payload consumed by the notification store and UI.
 * Callers usually pass `Omit<Notification, 'id'>` to `notify()`.
 */
export interface Notification {
  /** Internal unique identifier generated by the notification store. */
  id: number
  /** Visual variant for the notification. Defaults to `'info'`. */
  type?: 'info' | 'success' | 'warn' | 'danger'
  /** Text content displayed to the user. */
  message: string
  /**
   * Auto-dismiss delay in milliseconds.
   * Use `'never'` to keep the notification visible until it is replaced.
   * Defaults to `3000`.
   */
  duration?: number | 'never'
  /**
   * When `true`, the notification jumps to the front of the queue and replaces
   * the currently displayed notification immediately.
   */
  imperative?: boolean
  /** callback when disposed */
  onDispose?: () => void
}

type NotifyOptionsOrString = Omit<Notification, 'id'> | string
type Listener = () => void

const notificationQueue: Notification[] = []
const listeners = new Set<Listener>()

let id = 0
let current: Notification | null = null

// `useSyncExternalStore` requires a referentially stable snapshot when data
// hasn't changed. Returning `current` directly avoids creating a fresh object.
function getSnapshot() {
  return current
}

function subscribe(listener: Listener) {
  listeners.add(listener)

  return () => {
    listeners.delete(listener)
  }
}

function emitChange() {
  listeners.forEach((listener) => listener())
}

function dispose() {
  if (current === null) {
    return
  }

  runOnDispose(current.onDispose)
  current = null

  if (notificationQueue.length === 0) {
    emitChange()
    return
  }

  scheduleNext(false)
}

function runOnDispose(fn: Notification['onDispose']) {
  if (fn) {
    try {
      fn()
    } catch (error) {
      if (__DEV__) {
        console.error(
          'Failed to run callback:',
          error instanceof Error ? error.message : 'unknown reason'
        )
      }
    }
  }
}

function scheduleNext(imperative: boolean) {
  if (notificationQueue.length === 0) {
    return
  }

  if (!imperative && current !== null) {
    return
  }

  const next = notificationQueue.shift()

  if (next) {
    current = next
    emitChange()
  }
}

function normalizeNotification(
  optionsOrString: NotifyOptionsOrString
): Notification {
  const {
    type = 'info',
    message,
    duration = 3000,
    imperative = false,
    onDispose,
  } = typeof optionsOrString === 'string'
    ? { message: optionsOrString }
    : optionsOrString

  return {
    id: ++id,
    type,
    message,
    duration,
    imperative,
    onDispose,
  }
}

export function notify(optionsOrString: NotifyOptionsOrString) {
  const normalized = normalizeNotification(optionsOrString)

  if (normalized.imperative) {
    notificationQueue.unshift(normalized)
    scheduleNext(true)
  } else {
    notificationQueue.push(normalized)
    scheduleNext(false)
  }
}

export const notificationStore = {
  dispose,
  getSnapshot,
  subscribe,
}
